# BROWSER CONFIGURATION
BASE_URL : "https://hiring.cafe/"
TIMEOUT : 100000 # seconds
HEADERS:
  User-Agent: >-
    Mozilla/5.0 (Windows NT 10.0; Win64; x64)
    AppleWebKit/537.36 (KHTML, like Gecko)
    Chrome/122.0.0.0 Safari/537.36
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
  Accept-Language: "en-US,en;q=0.9"
  Referer: "https://hiring.cafe/"
  Connection: "keep-alive"

# Result_folder 
SAVE_ROOT_DIR : "crawled_data/"
